### PR TITLE
Check for global Ember in Node

### PR DESCRIPTION
**Pull request by joegoldbeck**
After the module.exports check (which presumably checks whether the architecture is Node-like), there is an implicit assumption that the 'ember' module is available. However, since 'ember' is not listed in the dependencies within package.json, this is a faulty assumption. In fact, including it in package.json would probably be a pretty bad idea anyway, since the Ember npm module hasn't been updated in a year. I suspect most people using Ember and Node (or in my case, Node + Browserify) are running Ember by directly requiring it from a local file, and would therefore have `Ember` in global scope, while a `require('ember')` would fail

### CODE REVIEW

**Comment by ryanflorence** [comment]
Hey @jgoldbeck,

Thanks for the pull request.

People using ember in commonjs environments should be shimming the global to act like a module so we can all leave these kinds of checks in the past :)

https://github.com/thlorenz/browserify-shim
https://github.com/jmreidy/grunt-browserify#shim

Also, ember will be on npm correctly eventually (according to members of the release team) and then nobody will have to shim it.

**Comment by joegoldbeck** [comment]
Thanks so much for your response @rpflorence! Looks like I can even shim it in right through browserify https://github.com/substack/node-browserify#brequirefile-opts

Solves the problem elegantly. Thanks for taking a look at my pull and pointing out a nicer solution.

**Comment by joegoldbeck** [comment]
Thanks for including dists for different formats @rpflorence! It turned out that the shim in node-browserify didn't consistently work, and browserify-shim seemed fairly complicated to add to my current build process, so I'd resigned myself to working off a fork to avoid spending too much time reworking my build process just now.

require('ic-ajax/dist/globals/main.js') now solves the problem perfectly, no fork required!

**Comment by ismyrnow** [comment]
I'm using browserify, and also ran into the issue @jgoldbeck did, with browserify-shim not working as expected. I wanted to avoid the full path with my `require` statement, so I installed via bower (Ember was already installed that way, and using browserify-shim), and added the following to my package.json:

``` javascript
"browser": {
  "ic-ajax": "./bower_components/ic-ajax/dist/globals/main.js"
}
"browserify-shim": {
    "ic-ajax": {
      "depends": [
        "ember:Ember"
      ]
    }
}
```

This allows me to just do `require('ic-ajax')`.

Hopeful that helps someone else coming across this issue.

**Pull request closed without merging**
